const express=require("express"),cors=require("cors"),fs=require("fs"),path=require("path"),jwt=require("jsonwebtoken"),bcrypt=require("bcryptjs");
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||"CHANGE_ME_IN_PRODUCTION";
const DATA=path.join(__dirname,"data"); fs.mkdirSync(DATA,{recursive:true});
const file=n=>path.join(DATA,n), read=n=>JSON.parse(fs.readFileSync(file(n),"utf8")), write=(n,v)=>fs.writeFileSync(file(n),JSON.stringify(v,null,2),"utf8");
for(const [n,def] of [["products.json",[]],["orders.json",[]],["expenses.json",[]],["accounts.json",[]],["journal.json",[]],["payments.json",[]],["purchases.json",[]],["suppliers.json",[]],["customers.json",[]],["inventory.json",[]],["bank-transactions.json",[]],["audit-log.json",[]],["users.json",[{username:"admin",password:"123456",role:"admin"}]],["settings.json",{profitPercent:10,payment:{number:"01065859268",iban:""},shipping:{provider:"Supplier/AliExpress"}}]])if(!fs.existsSync(file(n)))write(n,def);
app.use(cors());app.use(express.json({limit:"2mb"}));
function auth(req,res,next){const h=req.headers.authorization||"";try{req.user=jwt.verify(h.replace("Bearer ",""),SECRET);next()}catch{res.status(401).json({error:"Unauthorized"})}}
app.get("/api/health",(req,res)=>res.json({ok:true,service:"NIVORA SILVER"}));
app.post("/api/login.php",(req,res)=>{const u=read("users.json").find(x=>x.username===req.body.username);if(!u||req.body.password!==u.password)return res.status(401).json({error:"بيانات الدخول غير صحيحة"});res.json({token:jwt.sign({username:u.username,role:u.role},SECRET,{expiresIn:"12h"})})});
app.get("/api/products.php",auth,(req,res)=>res.json({products:read("products.json")}));
app.get("/api/orders.php",auth,(req,res)=>res.json({orders:read("orders.json")}));
app.get("/api/settings.php",auth,(req,res)=>res.json(read("settings.json")));
app.post("/api/settings.php",auth,(req,res)=>{const s=read("settings.json");s.profitPercent=Number(req.body.profitPercent||10);s.payment.number=req.body.vodafone||s.payment.number;s.payment.iban=req.body.iban||"";s.shipping.provider=req.body.shipping||s.shipping.provider;write("settings.json",s);res.json({ok:true})});
app.get("/api/dashboard.php",auth,(req,res)=>{const orders=read("orders.json"),expenses=read("expenses.json"),sales=orders.reduce((a,o)=>a+Number(o.total||0),0),cost=orders.reduce((a,o)=>a+Number(o.costTotal||0),0),exp=expenses.reduce((a,o)=>a+Number(o.amount||0),0);res.json({sales,cost,expenses:exp,profit:sales-cost-exp,orders:orders.length})});
app.post("/api/orders.php",(req,res)=>{const body=req.body;if(!body.customerName||!body.phone||!Array.isArray(body.items)||!body.items.length)return res.status(400).json({error:"بيانات الطلب ناقصة"});const products=read("products.json");let cost=0;for(const i of body.items){const p=products.find(x=>x.id===i.id);if(p)cost+=(Number(p.sourcePrice||0)+Number(p.shippingCost||0))*Number(i.qty||1)}const orders=read("orders.json"),id="NV-"+Date.now();const order={id,customerName:body.customerName,phone:body.phone,city:body.city||"",address:body.address||"",email:body.email||"",notes:body.notes||"",paymentReference:body.paymentReference||"",paymentStatus:"pending",status:"new",total:Number(body.total||0),costTotal:cost,profit:Number(body.total||0)-cost,items:body.items,createdAt:new Date().toISOString()};orders.push(order);write("orders.json",orders);res.status(201).json({ok:true,id})});
app.post("/api/aliexpress.php",auth,(req,res)=>{const url=String(req.body.url||"");if(!/^https?:\/\/(www\.)?aliexpress\.com\//i.test(url))return res.status(400).json({error:"رابط AliExpress غير صالح"});const queue=fs.existsSync(file("import-queue.json"))?read("import-queue.json"):[];queue.push({url,status:"pending",createdAt:new Date().toISOString()});write("import-queue.json",queue);res.json({ok:true,message:"تمت إضافة الرابط إلى قائمة الاستيراد. ربط API/DSers مطلوب لجلب الاسم والصور والسعر تلقائيًا."})});

const accounting=require("./api/accounting")({DATA,auth}); accounting.register(app);
app.patch("/api/orders.php/:id",auth,(req,res)=>{const orders=read("orders.json"),o=orders.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({error:"الطلب غير موجود"});const old=o.paymentStatus;o.paymentStatus=req.body.paymentStatus||o.paymentStatus;o.status=req.body.status||o.status;write("orders.json",orders);if(old!=="paid"&&o.paymentStatus==="paid"){const j=read("journal.json");const amount=Number(o.total||0),cost=Number(o.costTotal||0);j.push({id:"JE-"+Date.now()+"-SALE",date:new Date().toISOString(),description:"تحصيل طلب "+o.id,debitAccount:"1020",creditAccount:"4000",amount,reference:o.id});if(cost>0)j.push({id:"JE-"+Date.now()+"-COGS",date:new Date().toISOString(),description:"تكلفة مبيعات "+o.id,debitAccount:"5000",creditAccount:"1100",amount:cost,reference:o.id});write("journal.json",j);const ps=read("payments.json");ps.push({id:"PAY-"+Date.now(),orderId:o.id,method:"Vodafone Cash",amount,status:"paid",createdAt:new Date().toISOString()});write("payments.json",ps);const bank=read("bank-transactions.json"),prev=bank.length?Number(bank[bank.length-1].balance||0):0;bank.push({date:new Date().toISOString(),description:"تحصيل "+o.id,inflow:amount,outflow:0,balance:prev+amount,reference:o.id});write("bank-transactions.json",bank)}res.json({ok:true,order:o})});
app.listen(PORT,()=>console.log("NIVORA server running on "+PORT));
