(() => {
  const token=localStorage.getItem("nivora_admin_token"); if(!token){location.href="login.html";return;}
  const cfg=window.NIVORA_CONFIG||{MODE:"demo",API_BASE_URL:""}; const demo=localStorage.getItem("nivora_admin_mode")==="demo"||cfg.MODE==="demo";
  const money=n=>`${Number(n||0).toLocaleString("ar-EG")} ج.م`;
  const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
  const keys={accounts:"nivora_demo_accounts",journal:"nivora_demo_journal",payments:"nivora_demo_payments",purchases:"nivora_demo_purchases",suppliers:"nivora_demo_suppliers",bank:"nivora_demo_bank",expenses:"nivora_demo_expenses"};
  const read=(k,d=[])=>JSON.parse(localStorage.getItem(keys[k])||JSON.stringify(d)); const write=(k,v)=>localStorage.setItem(keys[k],JSON.stringify(v));
  function seed(){ if(!read("accounts").length) write("accounts",[{code:"1000",name:"الأصول",type:"asset"},{code:"1010",name:"الصندوق",type:"asset"},{code:"1020",name:"Vodafone Cash",type:"asset"},{code:"1030",name:"البنك",type:"asset"},{code:"1100",name:"المخزون",type:"asset"},{code:"1200",name:"العملاء",type:"asset"},{code:"2000",name:"الموردون",type:"liability"},{code:"3000",name:"رأس المال",type:"equity"},{code:"4000",name:"المبيعات",type:"revenue"},{code:"5000",name:"تكلفة المبيعات",type:"cogs"},{code:"5100",name:"مصروفات تشغيلية",type:"expense"},{code:"5200",name:"تسويق وإعلانات",type:"expense"},{code:"5300",name:"شحن",type:"expense"},{code:"5400",name:"عمولات دفع",type:"expense"}]); }
  seed();
  async function api(path,opts={}){if(demo)return demoApi(path,opts);const base=String(cfg.API_BASE_URL||"").replace(/\/$/,"");if(!base)throw Error("لم يتم ضبط عنوان الخادم.");const h={...(opts.headers||{}),Authorization:`Bearer ${token}`};const r=await fetch(`${base}/api/${path}`,{...opts,headers:h});const t=await r.text();let d;try{d=JSON.parse(t)}catch{throw Error("الخادم لم يُرجع JSON")};if(r.status===401){localStorage.removeItem("nivora_admin_token");location.href="login.html";return null}if(!r.ok)throw Error(d.error||"API error");return d}
  function demoApi(path,opts={}){let j=read("journal"),p=read("payments"),pu=read("purchases"),s=read("suppliers"),b=read("bank"),e=read("expenses");if(path==="accounting.php") {const body=opts.body?JSON.parse(opts.body):{}; if(opts.method==="POST"){if(body.action==="expense"){const id="EXP-"+Date.now();e.push({id,description:body.description,amount:Number(body.amount),account:body.account||"5100",createdAt:new Date().toISOString()});write("expenses",e);j.push({id:"JE-"+Date.now(),date:new Date().toISOString(),description:body.description,debitAccount:body.account||"5100",creditAccount:"1010",amount:Number(body.amount),reference:id});write("journal",j);b.push({date:new Date().toISOString(),description:body.description,inflow:0,outflow:Number(body.amount),balance:0,reference:id});write("bank",b);return Promise.resolve({ok:true})}}const sales=JSON.parse(localStorage.getItem("nivora_demo_orders")||"[]").filter(x=>x.paymentStatus==="paid"||x.status==="completed");const cost=sales.reduce((a,o)=>a+Number(o.costTotal||0),0),sale=sales.reduce((a,o)=>a+Number(o.total||0),0),exp=e.reduce((a,x)=>a+Number(x.amount||0),0);return Promise.resolve({summary:{sales:sale,cogs:cost,expenses:exp,profit:sale-cost-exp,orders:sales.length},accounts:read("accounts"),journal:j,payments:p,purchases:pu,suppliers:s,bank:b,inventory:[]})}return Promise.reject(Error("المسار غير متاح"))}
  function render(d){const s=d.summary||{};["sales","cogs","expenses","profit"].forEach(k=>{const el=document.getElementById(k);if(el)el.textContent=money(s[k])});
    const ov=document.getElementById("overview");if(ov)ov.innerHTML=`<div class="report-row"><span>الطلبات المدفوعة</span><b>${s.orders||0}</b></div><div class="report-row"><span>المبيعات</span><b>${money(s.sales)}</b></div><div class="report-row"><span>تكلفة المبيعات</span><b>${money(s.cogs)}</b></div><div class="report-row"><span>المصروفات</span><b>${money(s.expenses)}</b></div><div class="report-row"><span>صافي الربح</span><b>${money(s.profit)}</b></div>`;
    const journal=d.journal||[];document.getElementById("journal-table").innerHTML=journal.length?journal.slice().reverse().map(x=>`<tr><td>${new Date(x.date).toLocaleString("ar-EG")}</td><td>${esc(x.id)}</td><td>${esc(x.description)}</td><td>${esc(x.debitAccount)}</td><td>${esc(x.creditAccount)}</td><td>${money(x.amount)}</td><td>${esc(x.reference)}</td></tr>`).join(""):"<tr><td colspan=7 class=empty>لا توجد قيود.</td></tr>";
    document.getElementById("recent-journal").innerHTML=journal.slice(-8).reverse().map(x=>`<tr><td>${new Date(x.date).toLocaleDateString("ar-EG")}</td><td>${esc(x.description)}</td><td>${money(x.amount)}</td><td>${money(x.amount)}</td><td>${esc(x.reference)}</td></tr>`).join("")||"<tr><td colspan=5 class=empty>لا توجد قيود.</td></tr>";
    const acc=d.accounts||[];const balances={};journal.forEach(x=>{balances[x.debitAccount]=(balances[x.debitAccount]||0)+Number(x.amount||0);balances[x.creditAccount]=(balances[x.creditAccount]||0)-Number(x.amount||0)});document.getElementById("accounts-table").innerHTML=acc.map(a=>{const b=balances[a.code]||0;return `<tr><td>${a.code}</td><td>${esc(a.name)}</td><td>${esc(a.type)}</td><td>${money(b>0?b:0)}</td><td>${money(b<0?-b:0)}</td><td>${money(Math.abs(b))}</td></tr>`}).join("");
    document.getElementById("payments-table").innerHTML=(d.payments||[]).map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.orderId)}</td><td>${esc(x.method)}</td><td>${money(x.amount)}</td><td><span class=status>${esc(x.status)}</span></td></tr>`).join("")||"<tr><td colspan=5 class=empty>لا توجد مدفوعات.</td></tr>";
    document.getElementById("bank-table").innerHTML=(d.bank||[]).slice().reverse().map(x=>`<tr><td>${new Date(x.date).toLocaleDateString("ar-EG")}</td><td>${esc(x.description)}</td><td>${money(x.inflow)}</td><td>${money(x.outflow)}</td><td>${money(x.balance)}</td></tr>`).join("")||"<tr><td colspan=5 class=empty>لا توجد حركة.</td></tr>";
    document.getElementById("purchases-table").innerHTML=(d.purchases||[]).map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.supplierName)}</td><td>${money(x.productCost)}</td><td>${money(x.shippingCost)}</td><td>${money(x.total)}</td><td>${esc(x.status)}</td></tr>`).join("")||"<tr><td colspan=6 class=empty>لا توجد مشتريات.</td></tr>";
    document.getElementById("suppliers-table").innerHTML=(d.suppliers||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${x.orders||0}</td><td>${money(x.payable)}</td></tr>`).join("")||"<tr><td colspan=3 class=empty>لا يوجد موردون.</td></tr>";
    document.getElementById("income-report").innerHTML=`<div class=report-row><span>المبيعات</span><b>${money(s.sales)}</b></div><div class=report-row><span>تكلفة المبيعات</span><b>-${money(s.cogs)}</b></div><div class=report-row><span>مجمل الربح</span><b>${money((s.sales||0)-(s.cogs||0))}</b></div><div class=report-row><span>المصروفات</span><b>-${money(s.expenses)}</b></div><div class=report-row><span>صافي الربح</span><b>${money(s.profit)}</b></div>`;
    const inflow=(d.bank||[]).reduce((a,x)=>a+Number(x.inflow||0),0),outflow=(d.bank||[]).reduce((a,x)=>a+Number(x.outflow||0),0);document.getElementById("cash-report").innerHTML=`<div class=report-row><span>التدفقات الداخلة</span><b>${money(inflow)}</b></div><div class=report-row><span>التدفقات الخارجة</span><b>${money(outflow)}</b></div><div class=report-row><span>صافي التدفق</span><b>${money(inflow-outflow)}</b></div>`;
    document.getElementById("inventory-report").innerHTML=`<div class=report-row><span>عدد أصناف المخزون</span><b>${(d.inventory||[]).length}</b></div>`;document.getElementById("receivable-report").innerHTML=`<div class=report-row><span>العملاء</span><b>${(d.customers||[]).length}</b></div><div class=report-row><span>الموردون</span><b>${(d.suppliers||[]).length}</b></div>`;
  }
  async function load(){try{render(await api("accounting.php"))}catch(e){document.getElementById("accounting-msg").textContent=e.message}}
  document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab,.tab-panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById("tab-"+b.dataset.tab).classList.add("active")}));
  document.getElementById("expense-form").addEventListener("submit",async e=>{e.preventDefault();try{const body=Object.fromEntries(new FormData(e.currentTarget));await api("accounting.php",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"expense",...body})});e.currentTarget.reset();document.getElementById("expense-msg").textContent="تم تسجيل المصروف وإنشاء القيد ✓";await load()}catch(err){document.getElementById("expense-msg").textContent=err.message}});
  document.getElementById("logout")?.addEventListener("click",e=>{e.preventDefault();localStorage.removeItem("nivora_admin_token");localStorage.removeItem("nivora_admin_mode");location.href="login.html"});load();
})();